In [99]:
import numpy as np

# 8-Puzzle

#Problem definition


In [100]:
s_i = np.array([[0,1,2],[4,5,3],[7,8,6]])
print('s_i\n',s_i)
s_g = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_g\n',s_g)

s_i
 [[0 1 2]
 [4 5 3]
 [7 8 6]]
s_g
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


### Methods

In [101]:
def possible_actions(s):
        
        actions = []
        
        idx = np.argwhere(s == 0)
        
        if(idx[0,0]-1 >= 0):
            actions.append('down')
        
        if(idx[0,0]+1 <= 2):
            actions.append('up')
            
        if(idx[0,1]-1 >= 0):
            actions.append('right')
        
        if(idx[0,1]+1 <= 2):
            actions.append('left')
            
        
        
        return actions
    

def new_state(s,a):
        
        idx = np.argwhere(s == 0)
        new_s = s.copy()
        if(a == 'up'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0]+1,idx[0,1]]
            new_s[idx[0,0]+1,idx[0,1]] = 0
            
            
        if(a == 'down'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0]-1,idx[0,1]]
            new_s[idx[0,0]-1,idx[0,1]] = 0
            
        
        if(a == 'left'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0],idx[0,1]+1]
            new_s[idx[0,0],idx[0,1]+1] = 0
            
        
        if(a == 'right'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0],idx[0,1]-1]
            new_s[idx[0,0],idx[0,1]-1] = 0
            
            
        return new_s
    
    
    



In [102]:
print(possible_actions(s_i))

['up', 'left']


In [103]:
class Node:
    def __init__(self,father,state,action):
        self.father = father
        self.state = state
        self.action = action
        

In [104]:
from collections import deque
n = Node(None,s_i,None)
print('nodo inicial\n',n.state)
print('estado inicial\n',s_i)
print('estado final\n',s_g)

    
frontier = deque()
frontier.append(n)


explored = []

def child_explored(child,explored):
    
    
    
    for state in explored:
        if(np.array_equal(child,state) == True):
            return True
        
    
    return False
       
    
    
def child_frontier(child,frontier):
    
    

    for node in frontier:
        if(np.array_equal(child,node.state) == True):
            return True
    
    return False
            

     
level = 0        
final_child = None        
while(True):
    if len(frontier)==0:
        print('No hay solucion')
        break
    else:
        n = frontier.popleft()
        explored.append(n.state)
        
    solution = False
    for action in possible_actions(n.state):
        child = Node(n,new_state(n.state,action),action)
       
        if (child_explored(child.state,explored)==False and child_frontier(child.state,frontier)==False):
            if(np.array_equal(child.state,s_g)==True):
                
                solution = True
                final_child = child
                
                break

            frontier.append(child)
            
            
       
    if (solution == True):
        break


print('Preparando solucion...')        
node_aux = final_child
sol_actions  = []
while(node_aux.action != None):
    sol_actions.append(node_aux.action)
    node_aux = node_aux.father

print(list(reversed(sol_actions)))
    


nodo inicial
 [[0 1 2]
 [4 5 3]
 [7 8 6]]
estado inicial
 [[0 1 2]
 [4 5 3]
 [7 8 6]]
estado final
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
Preparando solucion...
['left', 'left', 'up', 'up']
