In [1]:
import numpy as np

# 8-Puzzle

#Problem definition


In [6]:
s_i = np.array([[1,2,3],[4,0,6],[7,5,8]])
print('s_i\n',s_i)
s_f = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_f\n',s_f)

s_i
 [[1 2 3]
 [4 0 6]
 [7 5 8]]
s_f
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


### Methods

In [7]:
actions = ['up','down','left','right']
def possible_actions(s):
    pass
def new_state(s,a):
    pass