In [1]:
import numpy as np

# 8-Puzzle

#Problem definition


In [70]:
s_i = np.array([[1,2,3],[4,5,6],[7,0,8]])
print('s_i\n',s_i)
s_g = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_g\n',s_g)

s_i
 [[1 2 3]
 [4 5 6]
 [7 0 8]]
s_g
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


### Methods

In [71]:
def possible_actions(s):
        
        actions = []
        
        idx = np.argwhere(s == 0)
        
        if(idx[0,0]-1 >= 0):
            actions.append('down')
        
        if(idx[0,0]+1 <= 2):
            actions.append('up')
            
        if(idx[0,1]-1 >= 0):
            actions.append('right')
        
        if(idx[0,1]+1 <= 2):
            actions.append('left')
            
        
        
        return actions
    

def new_state(s,a):
        
        idx = np.argwhere(s == 0)
        new_s = s.copy()
        if(a == 'up'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0]+1,idx[0,1]]
            new_s[idx[0,0]+1,idx[0,1]] = 0
            
            
        if(a == 'down'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0]-1,idx[0,1]]
            new_s[idx[0,0]-1,idx[0,1]] = 0
            
        
        if(a == 'left'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0],idx[0,1]+1]
            new_s[idx[0,0],idx[0,1]+1] = 0
            
        
        if(a == 'right'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0],idx[0,1]-1]
            new_s[idx[0,0],idx[0,1]-1] = 0
            
            
        return new_s
    
    
    



In [72]:
print(possible_actions(s_i))

['down', 'right', 'left']


In [50]:
s_2 = new_state(s_i,'right')


In [51]:
print(s_2)

[[1 2 3]
 [0 4 6]
 [7 5 8]]


In [63]:
class Node:
    def __init__(self,father,state):
        self.father = father
        self.state = state
        

In [77]:
from collections import deque
n = Node(None,s_i)
print('nodo inicial\n',n.state)
print('estado inicial\n',s_i)
print('estado final\n',s_g)

    
frontier = deque()
frontier.append(n)


explored = []

def child_explored(child,explored):
    
    
    
    for state in explored:
        if(np.array_equal(child,state) == True):
            return True
        
    
    return False
       
    
    
def child_frontier(child,frontier):
    
    

    for node in frontier:
        if(np.array_equal(child,node.state) == True):
            return True
    
    return False
            

            
while(True):
    if len(frontier)==0:
        
        break
    else:
        frontier.popleft()
        explored.append(n.state)
        
    
    for actions in possible_actions(s_i):
        print(actions)
        child = Node(n,actions)
        if (child_explored(child.state,explored)==False or child_frontier(child.state,frontier)==False):
            if(np.array_equal(child.state,s_g)==True):
                print('es la solucion')
                break
            
        else:
            
            print('iguales')
            break


        

nodo inicial
 [[1 2 3]
 [4 5 6]
 [7 0 8]]
estado inicial
 [[1 2 3]
 [4 5 6]
 [7 0 8]]
estado final
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
down
right
left
