In [1]:
import numpy as np

# 8-Puzzle

#Problem definition


In [197]:
s_i = np.array([[1,2,3],[4,6,0],[7,5,8]])
print('s_i\n',s_i)
s_f = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_f\n',s_f)

s_i
 [[1 2 3]
 [4 6 0]
 [7 5 8]]
s_f
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


### Methods

In [198]:


class PL:
    def possible_actions(s):
        
        actions = []
        
        idx = np.argwhere(s == 0)
        
        if(idx[0,0]-1 >= 0):
            actions.append('down')
        
        if(idx[0,0]+1 <= 2):
            actions.append('up')
            
        if(idx[0,1]-1 >= 0):
            actions.append('right')
        
        if(idx[0,1]+1 <= 2):
            actions.append('left')
            
        
        
        return actions
    
    def new_state(s,a):
        
        idx = np.argwhere(s == 0)
        
        if(a == 'up'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0]+1,idx[0,1]]
            s[idx[0,0]+1,idx[0,1]] = 0
            new_s = s
            
        if(a == 'down'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0]-1,idx[0,1]]
            s[idx[0,0]-1,idx[0,1]] = 0
            new_s = s
        
        if(a == 'left'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0],idx[0,1]+1]
            s[idx[0,0],idx[0,1]+1] = 0
            new_s = s
        
        if(a == 'right'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0],idx[0,1]-1]
            s[idx[0,0],idx[0,1]-1] = 0
            new_s = s
            
        return new_s

In [210]:
print(PL.possible_actions(s_i))

['up', 'left']


In [211]:
print(PL.new_state(s_i,'up'))


[[3 5 2]
 [0 6 4]
 [1 7 8]]
