In [1]:
import numpy as np
import time
from collections import deque

# 8-Puzzle

#Problem definition


In [2]:
s_i = np.array([[1,2,3],[0,5,6],[4,7,8]])
print('s_i\n',s_i)
s_g = np.array([[1,2,3],[4,5,6],[7,8,0]])
print('s_g\n',s_g)

s_i
 [[1 2 3]
 [0 5 6]
 [4 7 8]]
s_g
 [[1 2 3]
 [4 5 6]
 [7 8 0]]


### Methods

In [3]:
def possible_actions(s):
        
        actions = []
        
        idx = np.argwhere(s == 0)
        
        if(idx[0,0]-1 >= 0):
            actions.append('down')
        
        if(idx[0,0]+1 <= 2):
            actions.append('up')
            
        if(idx[0,1]-1 >= 0):
            actions.append('right')
        
        if(idx[0,1]+1 <= 2):
            actions.append('left')
            
        
        
        return actions
    

def new_state(s,a):
        
        idx = np.argwhere(s == 0)
        new_s = s.copy()
        if(a == 'up'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0]+1,idx[0,1]]
            new_s[idx[0,0]+1,idx[0,1]] = 0
            
            
        if(a == 'down'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0]-1,idx[0,1]]
            new_s[idx[0,0]-1,idx[0,1]] = 0
            
        
        if(a == 'left'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0],idx[0,1]+1]
            new_s[idx[0,0],idx[0,1]+1] = 0
            
        
        if(a == 'right'):
            new_s[idx[0,0],idx[0,1]] = new_s[idx[0,0],idx[0,1]-1]
            new_s[idx[0,0],idx[0,1]-1] = 0
            
            
        return new_s
    
    
def child_explored(child,explored):
    
    for state in explored:
        if(np.array_equal(child,state) == True):
            return True
        
    
    return False


def child_frontier(child,frontier):
    
    for node in frontier:
        if(np.array_equal(child,node.state) == True):
            return True
    
    return False


def cost_action(action):
    
    if(action == 'up'):
        cost = 1
        
    if(action == 'down'):
        cost = 1
        
    if(action == 'left'):
        cost = 1
        
    if(action == 'right'):
        cost = 1
    
    return cost


In [7]:
class Node:
    def __init__(self,parent,state,action,cost):
        self.parent = parent
        self.state = state
        self.action = action
        self.cost = cost
        
    def __lt__(self, other):
        return self.cost.__lt__(other.cost)
    def __gt__(self, other):
        return self.cost.__gt__(other.cost)
    def __eq__(self, other):
        return self.cost.__eq__(other.cost)
        

In [10]:
#BFS
start_time = time.time()
n = Node(None,s_i,None,None)
print('nodo inicial\n',n.state)
print('estado final\n',s_g)

    
frontier = deque()
frontier.append(n)
explored = []   
final_child = None

while(True):
    if len(frontier)==0:
        print('No hay solucion')
        break
    else:
        n = frontier.popleft()
        explored.append(n.state)
        
    solution = False
    for action in possible_actions(n.state):
        child = Node(n,new_state(n.state,action),action,cost_action(action))
       
        if (child_explored(child.state,explored)==False and child_frontier(child.state,frontier)==False):
            if(np.array_equal(child.state,s_g)==True):
                
                solution = True
                final_child = child
                
                break

            frontier.append(child)
            
       
    if (solution == True):
        break


print('Preparando solucion...')        
node_aux = final_child
sol_actions  = []
while(node_aux.action != None):
    sol_actions.append(node_aux.action)
    node_aux = node_aux.parent

print(list(reversed(sol_actions)))
end_time = time.time()
print ("Overall running time:", end_time - start_time)

nodo inicial
 [[1 2 3]
 [0 5 6]
 [4 7 8]]
estado final
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
Preparando solucion...
['up', 'left', 'left']
Overall running time: 0.004906415939331055


In [11]:
#uniform cost search
start_time = time.time()
n = Node(None,s_i,None,None)
print('nodo inicial\n',n.state)
print('estado final\n',s_g)

    
frontier = []
frontier.append(n)

explored = []   
final_child = None
final_cost = 0

while(True):
    if len(frontier)==0:
        print('No hay solucion')
        break
    else:
        n = frontier.pop(0)
        explored.append(n.state)
        
    solution = False
    for action in possible_actions(n.state):
        child = Node(n,new_state(n.state,action),action,cost_action(action))
        
        if (child_explored(child.state,explored)==False and child_frontier(child.state,frontier)==False):
            if(np.array_equal(child.state,s_g)==True):
                
                solution = True
                final_child = child
                
                break

            frontier.append(child)
    frontier = sorted(frontier)
            
                
                

       
    if (solution == True):
        break


print('Preparando solucion...')        
node_aux = final_child
sol_actions  = []

while(node_aux.action != None):
    sol_actions.append(node_aux.action)
    node_aux = node_aux.parent
    final_cost = final_cost + final_child.cost
   

print(list(reversed(sol_actions)))
print('el costo total es:',final_cost)
end_time = time.time()
print ("Overall running time:", end_time - start_time)

nodo inicial
 [[1 2 3]
 [0 5 6]
 [4 7 8]]
estado final
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
Preparando solucion...
['up', 'left', 'left']
el costo total es: 3
Overall running time: 0.007577419281005859


In [27]:
#DFS
start_time = time.time()
n = Node(None,s_i,None)
print('nodo inicial\n',n.state)
print('estado final\n',s_g)

    
frontier = deque()
frontier.append(n)
explored = []   
final_child = None

while(True):
    if len(frontier)==0:
        print('No hay solucion')
        break
    else:
        n = frontier.pop()
        explored.append(n.state)
        
    solution = False
    for action in possible_actions(n.state):
        child = Node(n,new_state(n.state,action),action)
       
        if (child_explored(child.state,explored)==False and child_frontier(child.state,frontier)==False):
            if(np.array_equal(child.state,s_g)==True):
                
                solution = True
                final_child = child
                print('hay solucion')
                break

            frontier.append(child)
            
       
    if (solution == True):
        break


print('Preparando solucion...')        
node_aux = final_child
sol_actions  = []
while(node_aux.action != None):
    sol_actions.append(node_aux.action)
    node_aux = node_aux.father

print(list(reversed(sol_actions)))
end_time = time.time()
print ("Overall running time:", end_time - start_time)

nodo inicial
 [[1 2 3]
 [0 5 6]
 [4 7 8]]
estado final
 [[1 2 3]
 [4 5 6]
 [7 8 0]]
hay solucion
Preparando solucion...
['left', 'left', 'up', 'right', 'right', 'down', 'left', 'left', 'up', 'right', 'right', 'down', 'left', 'left', 'up', 'right', 'right', 'down', 'left', 'left', 'up', 'right', 'right', 'down', 'left', 'left', 'up']
Overall running time: 0.03655648231506348
