In [161]:
import numpy as np

# 8-Puzzle

#Problem definition


In [162]:
s_i = np.array([[1,2,3],[4,6,0],[7,5,8]])
print('s_i\n',s_i)
s_g = np.array([[1,2,3],[4,0,6],[7,5,8]])
print('s_f\n',s_g)

s_i
 [[1 2 3]
 [4 6 0]
 [7 5 8]]
s_f
 [[1 2 3]
 [4 0 6]
 [7 5 8]]


### Methods

In [163]:
def possible_actions(s):
        
        actions = []
        
        idx = np.argwhere(s == 0)
        
        if(idx[0,0]-1 >= 0):
            actions.append('down')
        
        if(idx[0,0]+1 <= 2):
            actions.append('up')
            
        if(idx[0,1]-1 >= 0):
            actions.append('right')
        
        if(idx[0,1]+1 <= 2):
            actions.append('left')
            
        
        
        return actions
    

def new_state(s,a):
        
        idx = np.argwhere(s == 0)
        new_s = s.copy()
        if(a == 'up'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0]+1,idx[0,1]]
            s[idx[0,0]+1,idx[0,1]] = 0
            
            
        if(a == 'down'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0]-1,idx[0,1]]
            s[idx[0,0]-1,idx[0,1]] = 0
            
        
        if(a == 'left'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0],idx[0,1]+1]
            s[idx[0,0],idx[0,1]+1] = 0
            
        
        if(a == 'right'):
            s[idx[0,0],idx[0,1]] = s[idx[0,0],idx[0,1]-1]
            s[idx[0,0],idx[0,1]-1] = 0
            
            
        return new_s
    
    
    



In [164]:
print(possible_actions(s_i))

['down', 'up', 'right']


In [165]:
s_2 = new_state(s_i,'right')


[[1 2 3]
 [4 6 0]
 [7 5 8]]


In [166]:
print(s_2)

[[1 2 3]
 [4 6 0]
 [7 5 8]]


In [147]:
class Node:
    def __init__(self,father,state):
        self.father = father
        self.state = state
        

In [175]:
from collections import deque
n = Node(None,s_i)
print('n\n',n.state)
n1 = Node(n,new_s)
print('n1\n',n1.state)

if(np.array_equal(n.state,s_g)== True):
    print('estoy en la meta')
else:
    print('no estoy en la meta')
    
frontier = deque(['n','n2','n3'])
frontier.append('n4')
print(frontier)
frontier.popleft()
print(frontier)

explored = []

n
 [[1 2 3]
 [4 0 6]
 [7 5 8]]
n1
 [[1 2 3]
 [4 6 0]
 [7 5 8]]
estoy en la meta
deque(['n', 'n2', 'n3', 'n4'])
deque(['n2', 'n3', 'n4'])
